Add tool-binary resolution and error handling to wrappers

diff --git a/src/php-cs-diff b/src/php-cs-diff
--- a/src/php-cs-diff
+++ b/src/php-cs-diff
@@ -2,7 +2,20 @@
 
 THIS_DIR=$(dirname "${BASH_SOURCE[0]}")
 ROOT_DIR="$THIS_DIR/.."
-PHP_CS="$ROOT_DIR/bin/phpcs"
+
+if [ -z "$PHP_CS" ]; then
+  if test -f "$ROOT_DIR/bin/phpcs"; then
+      PHP_CS="$ROOT_DIR/bin/phpcs"
+  elif test -f "$THIS_DIR/phpcs"; then
+      PHP_CS="$THIS_DIR/phpcs"
+  else
+      echo "No PHP CodeSniffer executable set, and defaults not found in normal location." 1>&2
+      exit 1
+  fi
+elif ! test -f "$PHP_CS"; then
+  echo "PHP CodeSniffer executable $PHP_CS not found." 1>&2
+  exit 1
+fi
 
 SINCE_COMMIT=${1:-HEAD}
 
diff --git a/src/php-cs-fix b/src/php-cs-fix
--- a/src/php-cs-fix
+++ b/src/php-cs-fix
@@ -4,6 +4,20 @@ THIS_DIR=$(dirname "${BASH_SOURCE[0]}")
 ROOT_DIR="$THIS_DIR/.."
 PHP_CS_FIXER="$ROOT_DIR/bin/php-cs-fixer"
 
+if [ -z "$PHP_CS_FIXER" ]; then
+  if test -f "$ROOT_DIR/bin/php-cs-fixer"; then
+      PHP_CS_FIXER="$ROOT_DIR/bin/php-cs-fixer"
+  elif test -f "$THIS_DIR/php-cs-fixer"; then
+      PHP_CS_FIXER="$THIS_DIR/php-cs-fixer"
+  else
+      echo "No PHP CS Fixer executable set, and defaults not found in normal location." 1>&2
+      exit 1
+  fi
+elif ! test -f "$PHP_CS_FIXER"; then
+  echo "PHP CS Fixer executable $PHP_CS_FIXER not found." 1>&2
+  exit 1
+fi
+
 FILES=${1:-$(pwd)}
 
 
