Consolidate configs into config/ (standard.xml, fix-risky/fix-safe)

diff --git a/src/php-cs b/src/php-cs
--- a/src/php-cs
+++ b/src/php-cs
@@ -6,7 +6,17 @@ PHP_CS="$ROOT_DIR/bin/phpcs"
 
 FILES=${1:-$(pwd)}
 if [ -z "$PHP_CS_STANDARD" ]; then
-  PHP_CS_STANDARD="$ROOT_DIR/standards/ChristianBrown/ruleset.xml"
+  if test -f "$ROOT_DIR/config/standard.xml"; then
+      PHP_CS_STANDARD="$ROOT_DIR/config/standard.xml"
+  elif test -f "$ROOT_DIR/vendor/christianjbrown/php-code-quality-scripts/config/standard.xml"; then
+      PHP_CS_STANDARD="$ROOT_DIR/vendor/christianjbrown/php-code-quality-scripts/config/standard.xml"
+  else
+      echo "No PHP CodeSniffer standard set, and defaults not found in normal location." 1>&2
+      exit 1
+  fi
+elif ! test -f "$PHP_CS_STANDARD"; then
+  echo "PHP CodeSniffer standard $PHP_CS_STANDARD not found." 1>&2
+  exit 1
 fi
 
 echo "Running phpcs on $FILES with standard from $PHP_CS_STANDARD ..."
diff --git a/src/php-cs-fix-diff b/src/php-cs-fix-diff
--- a/src/php-cs-fix-diff
+++ b/src/php-cs-fix-diff
@@ -7,12 +7,32 @@ PHP_CS_FIXER="$ROOT_DIR/bin/php-cs-fixer"
 SINCE_COMMIT=${1:-HEAD}
 
 if [ -z "$PHP_CS_FIX_CONFIG_RISKY" ]; then
-  PHP_CS_FIX_CONFIG_RISKY=$ROOT_DIR/rule-sets/risky.php
-fi
-if [ -z "$PHP_CS_FIX_CONFIG_SAFE" ]; then
-  PHP_CS_FIX_CONFIG_SAFE=$ROOT_DIR/rule-sets/safe.php
+  if test -f "$ROOT_DIR/config/risky.php"; then
+      PHP_CS_FIX_CONFIG_RISKY="$ROOT_DIR/config/risky.php"
+  elif test -f "$ROOT_DIR/vendor/christianjbrown/php-code-quality-scripts/config/risky.php"; then
+      PHP_CS_FIX_CONFIG_RISKY="$ROOT_DIR/vendor/christianjbrown/php-code-quality-scripts/config/risky.php"
+  else
+      echo "No PHP CS Fixer risky rules file set, and defaults not found in normal location." 1>&2
+      exit 1
+  fi
+elif ! test -f "$PHP_CS_FIX_CONFIG_RISKY"; then
+  echo "PHP CS Fixer risky rules file $PHP_CS_FIX_CONFIG_RISKY not found." 1>&2
+  exit 1
 fi
 
+if [ -z "$PHP_CS_FIX_CONFIG_SAFE" ]; then
+  if test -f "$ROOT_DIR/config/safe.php"; then
+      PHP_CS_FIX_CONFIG_SAFE="$ROOT_DIR/config/safe.php"
+  elif test -f "$ROOT_DIR/vendor/christianjbrown/php-code-quality-scripts/config/safe.php"; then
+      PHP_CS_FIX_CONFIG_SAFE="$ROOT_DIR/vendor/christianjbrown/php-code-quality-scripts/config/safe.php"
+  else
+      echo "No PHP CS Fixer SAFE rules file set, and defaults not found in normal location." 1>&2
+      exit 1
+  fi
+elif ! test -f "$PHP_CS_FIX_CONFIG_SAFE"; then
+  echo "PHP CS Fixer SAFE rules file $PHP_CS_FIX_CONFIG_SAFE not found." 1>&2
+  exit 1
+fi
 
 function fix() {
 	if [[ $1 == *\.php ]]; then
